title: Kelton Watts
logo: /assets/img/headshot.jpg
description: 
  Phone":" (425) 287-0242\n
  Email":" keltonwatts@outlook.com\n
  LinkedIn":" https://www.linkedin.com/in/kelton-watts/"
theme: jekyll-theme-minimal
