title: Kelton Watts
logo: /assets/img/headshot.jpg
description: I am a student at Grinnell College studying Computer Science and Math. At Grinnell I enjoy playing Baseball for Grinnell and spending my time as the president of Gateway, a Christian organization dedicated to creating a place for students to have honest conversations about their faith, troubles, and growth. I am excited to expand my knowledge of computers and the software they run on to create meaningful tools that impact lives.
#show_downloads:
theme: jekyll-theme-minimal
